/*
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 */
//! `UITableView`, `UITableViewCell`.

use crate::frameworks::core_graphics::{CGPoint, CGRect, CGSize};
use crate::frameworks::foundation::{NSInteger, NSUInteger};
use crate::frameworks::uikit::ui_view;
use crate::frameworks::uikit::ui_view::ui_scroll_view::UIScrollViewHostObject;
use crate::frameworks::uikit::ui_view_controller::UIViewControllerHostObject;
use crate::objc::{
    id, impl_HostObject_with_superclass, msg, msg_class, msg_super, nil, objc_classes, release,
    retain, ClassExports, NSZonePtr,
};

#[derive(Default)]
struct UITableViewControllerHostObject {
    superclass: UIViewControllerHostObject,
    /// `UITableViewStyle` passed to `-initWithStyle:` (0 = plain, 1 = grouped),
    /// used by `-loadView` when it lazily creates the managed table view.
    style: i32,
}
impl_HostObject_with_superclass!(UITableViewControllerHostObject);

pub struct UITableViewCellHostObject {
    superclass: ui_view::UIViewHostObject, // <-- Убираем super::
    content_view: id,
    /// Lazily-created default subviews (UIKit's built-in cell labels/image),
    /// each retained while it lives here. `nil` until first requested.
    text_label: id,
    detail_text_label: id,
    image_view: id,
}
impl_HostObject_with_superclass!(UITableViewCellHostObject);
impl Default for UITableViewCellHostObject {
    fn default() -> Self {
        UITableViewCellHostObject {
            superclass: Default::default(),
            content_view: nil,
            text_label: nil,
            detail_text_label: nil,
            image_view: nil,
        }
    }
}

pub struct UITableViewHostObject {
    /// Inherits all UIScrollView (and therefore UIView) state. Without this
    /// field the table view's host object would not be borrow-compatible with
    /// the superclass methods, which would route through the use-after-free
    /// fallback and corrupt rendering.
    superclass: UIScrollViewHostObject,
    /// Non-retained delegate (`UITableViewDelegate`).
    table_delegate: id,
    /// Non-retained data source (`UITableViewDataSource`).
    data_source: id,
    /// Cells currently laid out, top-to-bottom in the order generated by
    /// `reloadData`. Each cell is retained while it is in this list.
    cells: Vec<id>,
    /// Index paths matching `cells` 1:1.
    cell_index_paths: Vec<id>,
    row_height: f32,
    section_header_height: f32,
    section_footer_height: f32,
    separator_style: NSInteger,
    separator_color: id,
    table_header_view: id,
    table_footer_view: id,
    /// Whether we have performed the implicit first `reloadData`. UIKit
    /// reloads a table the first time it lays out with a data source; touchHLE
    /// has no automatic layout pass, so we trigger that reload ourselves the
    /// first time the table has both a data source and a non-zero size.
    auto_reloaded: bool,
}
impl Default for UITableViewHostObject {
    fn default() -> Self {
        UITableViewHostObject {
            superclass: Default::default(),
            table_delegate: nil,
            data_source: nil,
            cells: Vec::new(),
            cell_index_paths: Vec::new(),
            row_height: 44.0,
            section_header_height: 22.0,
            section_footer_height: 0.0,
            separator_style: 1, // UITableViewCellSeparatorStyleSingleLine
            separator_color: nil,
            table_header_view: nil,
            table_footer_view: nil,
            auto_reloaded: false,
        }
    }
}
impl_HostObject_with_superclass!(UITableViewHostObject);

/// Perform the implicit first `reloadData` that UIKit does during a table's
/// first layout. Called whenever the data source or size changes; only fires
/// once, and only once both a data source and a usable size are available.
fn maybe_auto_reload(env: &mut crate::Environment, this: id) {
    {
        let host = env.objc.borrow::<UITableViewHostObject>(this);
        if host.auto_reloaded || host.data_source == nil {
            return;
        }
    }
    let bounds: CGRect = msg![env; this bounds];
    let (bw, bh) = (bounds.size.width, bounds.size.height);
    if bw <= 0.0 || bh <= 0.0 {
        return;
    }
    env.objc.borrow_mut::<UITableViewHostObject>(this).auto_reloaded = true;
    () = msg![env; this reloadData];
}

/// Drop the cell list and (optionally) remove the cell views from the table.
fn clear_cells(env: &mut crate::Environment, this: id, remove_subviews: bool) {
    // Take both vectors out so we can release without nested borrows.
    let (cells, paths) = {
        let host = env.objc.borrow_mut::<UITableViewHostObject>(this);
        (
            std::mem::take(&mut host.cells),
            std::mem::take(&mut host.cell_index_paths),
        )
    };
    for cell in cells {
        if remove_subviews {
            let _: () = msg![env; cell removeFromSuperview];
        }
        release(env, cell);
    }
    for path in paths {
        release(env, path);
    }
}

fn make_rect(x: f32, y: f32, w: f32, h: f32) -> CGRect {
    CGRect {
        origin: CGPoint { x, y },
        size: CGSize { width: w, height: h },
    }
}

/// Position a `UITableViewCell`'s built-in content view, image view and text
/// labels, mirroring UIKit's default cell layout closely enough to be
/// recognisable: the optional image sits on the left and the text label fills
/// the remaining width. touchHLE has no automatic layout pass, so this is
/// invoked whenever the cell's frame changes or a default subview is created.
fn layout_cell_contents(env: &mut crate::Environment, this: id) {
    let bounds: CGRect = msg![env; this bounds];
    let (w, h) = (bounds.size.width, bounds.size.height);
    let (content_view, image_view, text_label, detail_label) = {
        let host = env.objc.borrow::<UITableViewCellHostObject>(this);
        (
            host.content_view,
            host.image_view,
            host.text_label,
            host.detail_text_label,
        )
    };

    if content_view != nil {
        () = msg![env; content_view setFrame:(make_rect(0.0, 0.0, w, h))];
    }

    let mut text_x = 10.0;
    if image_view != nil {
        let image: id = msg![env; image_view image];
        if image != nil && h > 0.0 {
            () = msg![env; image_view setFrame:(make_rect(0.0, 0.0, h, h))];
            text_x = h + 10.0;
        } else {
            () = msg![env; image_view setFrame:(make_rect(0.0, 0.0, 0.0, 0.0))];
        }
    }

    let text_w = (w - text_x - 10.0).max(0.0);
    if text_label != nil && detail_label != nil {
        // Two-line cell: stack the title over the detail text.
        () = msg![env; text_label setFrame:(make_rect(text_x, 0.0, text_w, h * 0.6))];
        () = msg![env; detail_label setFrame:(make_rect(text_x, h * 0.6, text_w, h * 0.4))];
    } else if text_label != nil {
        () = msg![env; text_label setFrame:(make_rect(text_x, 0.0, text_w, h))];
    }
}

/// Lazily create one of the cell's default subviews (a `UILabel` or
/// `UIImageView`) with a transparent background so the cell shows through,
/// add it to the content view, and store it in `slot`.
fn ensure_cell_subview(env: &mut crate::Environment, this: id, class_name: &str) -> id {
    let content_view = env.objc.borrow::<UITableViewCellHostObject>(this).content_view;
    let class = env.objc.get_known_class(class_name, &mut env.mem);
    let view: id = msg![env; class alloc];
    let view: id = msg![env; view init];
    let clear: id = msg_class![env; UIColor clearColor];
    () = msg![env; view setBackgroundColor:clear];
    retain(env, view);
    if content_view != nil {
        () = msg![env; content_view addSubview:view];
    }
    view
}

pub const CLASSES: ClassExports = objc_classes! {

(env, this, _cmd);

// Добавляем приватный класс, на который ругается NIB-декодер
@implementation UITableViewCellContentView: UIView

- (id)initWithFrame:(CGRect)frame {
    msg_super![env; this initWithFrame:frame]
}

- (id)initWithCoder:(id)coder {
    msg_super![env; this initWithCoder:coder]
}

@end

@implementation UITableViewCell: UIView

+ (id)allocWithZone:(NSZonePtr)_zone {
    let host_object = Box::<UITableViewCellHostObject>::default();
    env.objc.alloc_object(this, host_object, &mut env.mem)
}

- (id)initWithFrame:(CGRect)frame {
    let this: id = msg_super![env; this initWithFrame:frame];

    // Честно создаем внутренний content_view.
    // Передаем имя класса напрямую в макрос msg_class!
    let content_view: id = msg_class![env; UITableViewCellContentView alloc];
    let content_view: id = msg![env; content_view initWithFrame:frame];

    // Добавляем его как subview (как в iOS)
    () = msg![env; this addSubview:content_view];

    env.objc.borrow_mut::<UITableViewCellHostObject>(this).content_view = content_view;
    this
}

- (id)initWithStyle:(i32)_style reuseIdentifier:(id)_identifier {
    let frame = <CGRect as Default>::default();
    msg![env; this initWithFrame:frame]
}

// `-[UITableViewCell initWithFrame:reuseIdentifier:]` is the iOS 2.x
// designated initializer, deprecated in iOS 3.0 in favour of
// `-initWithStyle:reuseIdentifier:`. The header (UIKit's
// `UITableViewCell.h`) still ships the symbol, and several legacy 32-bit
// games (e.g. Cooking Fever, Dungeon Shooter) call it. Apple's reference
// implementation routes it through the frame-only initializer and
// records the reuse identifier — the reuse identifier itself is held by
// the cell so that `+[UITableView dequeueReusableCellWithIdentifier:]`
// can later match it. <https://developer.apple.com/documentation/uikit/uitableviewcell/1623200-initwithframe>
- (id)initWithFrame:(CGRect)frame reuseIdentifier:(id)_identifier {
    msg![env; this initWithFrame:frame]
}

- (id)initWithCoder:(id)coder {
    let this: id = msg_super![env; this initWithCoder:coder];
    // При загрузке из NIB contentView обычно уже внутри (как под-вьюха).
    // Мы можем просто инициализировать поле, если NIB его создал,
    // но для безопасности создадим пустой, если его нет.
    let frame = <CGRect as Default>::default();

    // Исправлено здесь: убран get_known_class и переменная, имя класса передано
    // напрямую
    let content_view: id = msg_class![env; UITableViewCellContentView alloc];
    let content_view: id = msg![env; content_view initWithFrame:frame];

    () = msg![env; this addSubview:content_view];
    env.objc.borrow_mut::<UITableViewCellHostObject>(this).content_view = content_view;
    this
}

- (())dealloc {
    let (content_view, text_label, detail_label, image_view) = {
        let host = env.objc.borrow::<UITableViewCellHostObject>(this);
        (host.content_view, host.text_label, host.detail_text_label, host.image_view)
    };
    release(env, content_view);
    if text_label != nil { release(env, text_label); }
    if detail_label != nil { release(env, detail_label); }
    if image_view != nil { release(env, image_view); }
    msg_super![env; this dealloc]
}

- (id)reuseIdentifier { nil }

- (id)textLabel {
    let existing = env.objc.borrow::<UITableViewCellHostObject>(this).text_label;
    if existing != nil {
        return existing;
    }
    let label = ensure_cell_subview(env, this, "UILabel");
    env.objc.borrow_mut::<UITableViewCellHostObject>(this).text_label = label;
    layout_cell_contents(env, this);
    label
}

- (id)detailTextLabel {
    let existing = env.objc.borrow::<UITableViewCellHostObject>(this).detail_text_label;
    if existing != nil {
        return existing;
    }
    let label = ensure_cell_subview(env, this, "UILabel");
    env.objc.borrow_mut::<UITableViewCellHostObject>(this).detail_text_label = label;
    layout_cell_contents(env, this);
    label
}

- (id)imageView {
    let existing = env.objc.borrow::<UITableViewCellHostObject>(this).image_view;
    if existing != nil {
        return existing;
    }
    let iv = ensure_cell_subview(env, this, "UIImageView");
    env.objc.borrow_mut::<UITableViewCellHostObject>(this).image_view = iv;
    layout_cell_contents(env, this);
    iv
}

- (())setFrame:(CGRect)frame {
    () = msg_super![env; this setFrame:frame];
    layout_cell_contents(env, this);
}

- (())layoutSubviews {
    () = msg_super![env; this layoutSubviews];
    layout_cell_contents(env, this);
}

// Теперь возвращаем реальный contentView, а не this
- (id)contentView {
    env.objc.borrow::<UITableViewCellHostObject>(this).content_view
}

- (id)accessoryView { nil }
- (())setAccessoryView:(id)_view {}
- (i32)accessoryType { 0 }
- (())setAccessoryType:(i32)_type {}
- (i32)selectionStyle { 0 }
- (())setSelectionStyle:(i32)_style {}
- (bool)isSelected { false }
- (())setSelected:(bool)_selected {}
- (())setSelected:(bool)_selected animated:(bool)_animated {}
- (bool)isHighlighted { false }
- (())setHighlighted:(bool)_highlighted {}
- (())setHighlighted:(bool)_highlighted animated:(bool)_animated {}
- (())prepareForReuse {}
- (id)backgroundView { nil }
- (())setBackgroundView:(id)_view {}
- (id)selectedBackgroundView { nil }
- (())setSelectedBackgroundView:(id)_view {}
- (())setEditing:(bool)_editing animated:(bool)_animated {}
- (bool)isEditing { false }
- (i32)editingStyle { 0 }
- (bool)showingDeleteConfirmation { false }
- (())setIndentationLevel:(i32)_level {}
- (i32)indentationLevel { 0 }

@end

@implementation UIProgressView: UIView

- (id)initWithFrame:(CGRect)frame {
    msg_super![env; this initWithFrame:frame]
}

- (id)initWithProgressViewStyle:(i32)_style {
    msg_super![env; this init]
}

- (f32)progress { 0.0 }
- (())setProgress:(f32)_progress {}
- (())setProgress:(f32)_progress animated:(bool)_animated {}
- (i32)progressViewStyle { 0 }
- (())setProgressViewStyle:(i32)_style {}
- (id)progressTintColor { nil }
- (())setProgressTintColor:(id)_color {}
- (id)trackTintColor { nil }
- (())setTrackTintColor:(id)_color {}
- (id)progressImage { nil }
- (())setProgressImage:(id)_image {}
- (id)trackImage { nil }
- (())setTrackImage:(id)_image {}

@end

@implementation UITableView: UIScrollView

+ (id)allocWithZone:(NSZonePtr)_zone {
    let host_object = Box::<UITableViewHostObject>::default();
    env.objc.alloc_object(this, host_object, &mut env.mem)
}

- (id)initWithFrame:(CGRect)frame style:(i32)_style {
    msg_super![env; this initWithFrame:frame]
}

- (())dealloc {
    clear_cells(env, this, false);
    let header = env.objc.borrow::<UITableViewHostObject>(this).table_header_view;
    let footer = env.objc.borrow::<UITableViewHostObject>(this).table_footer_view;
    let separator_color = env.objc.borrow::<UITableViewHostObject>(this).separator_color;
    if header != nil { release(env, header); }
    if footer != nil { release(env, footer); }
    if separator_color != nil { release(env, separator_color); }
    msg_super![env; this dealloc]
}

- (id)visibleCells {
    // We don't track visibility separately from layout, so report every cell
    // currently materialised by -reloadData.
    let cells = env.objc.borrow::<UITableViewHostObject>(this).cells.clone();
    let array: id = msg_class![env; NSMutableArray array];
    for cell in cells {
        () = msg![env; array addObject:cell];
    }
    array
}

- (id)delegate {
    env.objc.borrow::<UITableViewHostObject>(this).table_delegate
}
- (())setDelegate:(id)delegate {
    env.objc.borrow_mut::<UITableViewHostObject>(this).table_delegate = delegate;
}
- (id)dataSource {
    env.objc.borrow::<UITableViewHostObject>(this).data_source
}
- (())setDataSource:(id)data_source {
    env.objc.borrow_mut::<UITableViewHostObject>(this).data_source = data_source;
    maybe_auto_reload(env, this);
}

- (())setFrame:(CGRect)frame {
    () = msg_super![env; this setFrame:frame];
    maybe_auto_reload(env, this);
}

- (())setBounds:(CGRect)bounds {
    () = msg_super![env; this setBounds:bounds];
    maybe_auto_reload(env, this);
}

- (())reloadData {
    // Drop existing cells before recreating them.
    clear_cells(env, this, true);

    let data_source = env.objc.borrow::<UITableViewHostObject>(this).data_source;
    if data_source == nil {
        return;
    }

    let bounds: CGRect = msg![env; this bounds];
    let width = bounds.size.width;
    let row_height = env.objc.borrow::<UITableViewHostObject>(this).row_height;

    // Section count defaults to 1 if the data source does not implement
    // -numberOfSectionsInTableView:.
    let sel_num_sections = env.objc.lookup_selector("numberOfSectionsInTableView:");
    let mut num_sections: NSInteger = 1;
    if let Some(sel) = sel_num_sections {
        let responds: bool = msg![env; data_source respondsToSelector:sel];
        if responds {
            num_sections = msg![env; data_source numberOfSectionsInTableView:this];
        }
    }

    let mut y: f32 = 0.0;
    let header = env.objc.borrow::<UITableViewHostObject>(this).table_header_view;
    if header != nil {
        let mut frame: CGRect = msg![env; header frame];
        let h = frame.size.height.max(0.0);
        frame.origin = CGPoint { x: 0.0, y };
        frame.size.width = width;
        () = msg![env; header setFrame:frame];
        () = msg![env; this addSubview:header];
        y += h;
    }

    let mut new_cells: Vec<id> = Vec::new();
    let mut new_paths: Vec<id> = Vec::new();

    for section in 0..num_sections {
        let row_count: NSInteger = msg![env; data_source
            tableView:this
            numberOfRowsInSection:section];
        for row in 0..row_count {
            let index_path: id = msg_class![env; NSIndexPath
                indexPathForRow:(row as NSUInteger)
                inSection:(section as NSUInteger)];
            retain(env, index_path);

            let cell: id = msg![env; data_source
                tableView:this
                cellForRowAtIndexPath:index_path];
            if cell == nil {
                release(env, index_path);
                continue;
            }
            retain(env, cell);

            let frame = CGRect {
                origin: CGPoint { x: 0.0, y },
                size: CGSize { width, height: row_height },
            };
            () = msg![env; cell setFrame:frame];
            () = msg![env; this addSubview:cell];

            y += row_height;
            new_cells.push(cell);
            new_paths.push(index_path);
        }
    }

    let footer = env.objc.borrow::<UITableViewHostObject>(this).table_footer_view;
    if footer != nil {
        let mut frame: CGRect = msg![env; footer frame];
        let h = frame.size.height.max(0.0);
        frame.origin = CGPoint { x: 0.0, y };
        frame.size.width = width;
        () = msg![env; footer setFrame:frame];
        () = msg![env; this addSubview:footer];
        y += h;
    }

    {
        let host = env.objc.borrow_mut::<UITableViewHostObject>(this);
        host.cells = new_cells;
        host.cell_index_paths = new_paths;
    }

    let content_size = CGSize { width, height: y };
    () = msg![env; this setContentSize:content_size];
}

- (())reloadSections:(id)_sections withRowAnimation:(i32)_animation {
    () = msg![env; this reloadData];
}
- (())reloadRowsAtIndexPaths:(id)_paths withRowAnimation:(i32)_animation {
    () = msg![env; this reloadData];
}
- (i32)numberOfSections {
    let data_source = env.objc.borrow::<UITableViewHostObject>(this).data_source;
    if data_source == nil { return 0; }
    let sel = match env.objc.lookup_selector("numberOfSectionsInTableView:") {
        Some(sel) => sel,
        None => return 1,
    };
    let responds: bool = msg![env; data_source respondsToSelector:sel];
    if !responds { return 1; }
    msg![env; data_source numberOfSectionsInTableView:this]
}
- (i32)numberOfRowsInSection:(i32)section {
    let data_source = env.objc.borrow::<UITableViewHostObject>(this).data_source;
    if data_source == nil { return 0; }
    msg![env; data_source tableView:this numberOfRowsInSection:section]
}
- (id)cellForRowAtIndexPath:(id)path {
    if path == nil { return nil; }
    let cell_paths = env.objc.borrow::<UITableViewHostObject>(this).cell_index_paths.clone();
    for (i, other) in cell_paths.into_iter().enumerate() {
        let equal: bool = msg![env; path isEqual:other];
        if equal {
            return env.objc.borrow::<UITableViewHostObject>(this).cells[i];
        }
    }
    nil
}
- (id)dequeueReusableCellWithIdentifier:(id)_identifier {
    // We don't keep a reuse pool; returning nil forces the data source to
    // create a fresh cell, which is always valid per Apple's API.
    nil
}
- (id)indexPathForCell:(id)cell {
    if cell == nil { return nil; }
    let host = env.objc.borrow::<UITableViewHostObject>(this);
    for (i, &c) in host.cells.iter().enumerate() {
        if c == cell {
            return host.cell_index_paths[i];
        }
    }
    nil
}
- (id)indexPathForSelectedRow { nil }
- (id)indexPathsForSelectedRows { nil }
- (())selectRowAtIndexPath:(id)_path animated:(bool)_animated scrollPosition:(i32)_pos {}
- (())deselectRowAtIndexPath:(id)_path animated:(bool)_animated {}
- (())scrollToRowAtIndexPath:(id)_path atScrollPosition:(i32)_pos animated:(bool)_animated {}
- (())setEditing:(bool)_editing animated:(bool)_animated {}
- (bool)isEditing { false }
- (())setAllowsSelection:(bool)_allows {}
- (bool)allowsSelection { true }
- (())setAllowsMultipleSelection:(bool)_allows {}
- (())setRowHeight:(f32)height {
    env.objc.borrow_mut::<UITableViewHostObject>(this).row_height = height;
}
- (f32)rowHeight {
    env.objc.borrow::<UITableViewHostObject>(this).row_height
}
- (())setSectionHeaderHeight:(f32)height {
    env.objc.borrow_mut::<UITableViewHostObject>(this).section_header_height = height;
}
- (())setSectionFooterHeight:(f32)height {
    env.objc.borrow_mut::<UITableViewHostObject>(this).section_footer_height = height;
}
- (id)tableHeaderView {
    env.objc.borrow::<UITableViewHostObject>(this).table_header_view
}
- (())setTableHeaderView:(id)view {
    if view != nil { retain(env, view); }
    let old = std::mem::replace(
        &mut env.objc.borrow_mut::<UITableViewHostObject>(this).table_header_view,
        view,
    );
    if old != nil { release(env, old); }
}
- (id)tableFooterView {
    env.objc.borrow::<UITableViewHostObject>(this).table_footer_view
}
- (())setTableFooterView:(id)view {
    if view != nil { retain(env, view); }
    let old = std::mem::replace(
        &mut env.objc.borrow_mut::<UITableViewHostObject>(this).table_footer_view,
        view,
    );
    if old != nil { release(env, old); }
}
- (())setSeparatorStyle:(i32)style {
    env.objc.borrow_mut::<UITableViewHostObject>(this).separator_style = style as NSInteger;
}
- (i32)separatorStyle {
    env.objc.borrow::<UITableViewHostObject>(this).separator_style
}
- (())setSeparatorColor:(id)color {
    if color != nil { retain(env, color); }
    let old = std::mem::replace(
        &mut env.objc.borrow_mut::<UITableViewHostObject>(this).separator_color,
        color,
    );
    if old != nil { release(env, old); }
}
- (id)separatorColor {
    env.objc.borrow::<UITableViewHostObject>(this).separator_color
}
- (())registerClass:(id)_class forCellReuseIdentifier:(id)_identifier {}
- (())registerNib:(id)_nib forCellReuseIdentifier:(id)_identifier {}
- (())beginUpdates {}
- (())endUpdates {}
- (())insertRowsAtIndexPaths:(id)_paths withRowAnimation:(i32)_animation {
    () = msg![env; this reloadData];
}
- (())deleteRowsAtIndexPaths:(id)_paths withRowAnimation:(i32)_animation {
    () = msg![env; this reloadData];
}

@end

@implementation UITableViewController: UIViewController

+ (id)allocWithZone:(NSZonePtr)_zone {
    let host_object = Box::<UITableViewControllerHostObject>::default();
    env.objc.alloc_object(this, host_object, &mut env.mem)
}

- (id)initWithStyle:(i32)style {
    let this: id = msg_super![env; this init];
    env.objc.borrow_mut::<UITableViewControllerHostObject>(this).style = style;
    this
}

// Честный iOS-подход: переопределяем создание вьюхи по умолчанию.
// Если NIB'а нет, мы принудительно создаем UITableView, а не UIView.
- (())loadView {
    let frame = <CGRect as Default>::default();
    let style = env.objc.borrow::<UITableViewControllerHostObject>(this).style;
    let table_view: id = msg_class![env; UITableView alloc];
    let table_view: id = msg![env; table_view initWithFrame:frame style:style];

    // UITableViewController owns its table view and, per UIKit, makes itself
    // both the data source and the delegate. Without this the table never asks
    // the controller for any rows and renders empty (a blank white screen).
    () = msg![env; table_view setDataSource:this];
    () = msg![env; table_view setDelegate:this];

    // Устанавливаем таблицу как главную view этого контроллера
    () = msg![env; this setView:table_view];
    release(env, table_view);
}

// Теперь tableView ссылается на реальный UITableView
- (id)tableView {
    msg![env; this view]
}

- (())setTableView:(id)view {
    () = msg![env; this setView:view];
}

- (bool)clearsSelectionOnViewWillAppear { true }
- (())setClearsSelectionOnViewWillAppear:(bool)_clears {}

@end

};
