name: Build touchHLE

on:
  push:
    branches: [ "trunk" ]
  pull_request:
    branches: [ "trunk" ]
  create:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-android:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout touchHLE
      shell: bash
      run: |
        mkdir -p "$GITHUB_WORKSPACE"
        git clone https://github.com/touchHLE/touchHLE "$GITHUB_WORKSPACE"
        cd "$GITHUB_WORKSPACE"
        git fetch origin "$GITHUB_REF"
        git checkout "$GITHUB_SHA"

    - name: Check formatting
      run: dev-scripts/format.sh --check

    - name: Get Submodules
      run: git submodule update --init

    # ---------- Boost ----------
    - name: Try to get cached copy of Boost
      id: cache-boost
      uses: actions/cache@v3
      with:
        path: vendor/boost
        key: boost_1_81_0

    - if: ${{ steps.cache-boost.outputs.cache-hit != 'true' }}
      name: Download Boost
      run: curl -L -o boost_1_81_0.7z "https://archives.boost.io/release/1.81.0/source/boost_1_81_0.7z"

    - if: ${{ steps.cache-boost.outputs.cache-hit != 'true' }}
      name: Extract Boost
      run: 7z -ovendor x boost_1_81_0.7z && mv vendor/boost_1_81_0 vendor/boost

    # ---------- CMake ----------
    - name: Try to get cached copy of cmake
      id: cache-cmake
      uses: actions/cache@v3
      with:
        path: vendor/cmake
        key: cmake_3_31_6_linux

    - if: ${{ steps.cache-cmake.outputs.cache-hit != 'true' }}
      name: Download Cmake
      run: curl -L -O "https://github.com/Kitware/CMake/releases/download/v3.31.6/cmake-3.31.6-linux-x86_64.tar.gz"

    - if: ${{ steps.cache-cmake.outputs.cache-hit != 'true' }}
      name: Extract Cmake
      run: tar xzvf "cmake-3.31.6-linux-x86_64.tar.gz" -C vendor && mv vendor/cmake-3.31.6-linux-x86_64 vendor/cmake

    # ---------- Rust 32-bit ----------
    - name: Install ARMv7 Android Rust toolchain (32-bit)
      run: rustup target add armv7-linux-androideabi

    - name: Install cargo-ndk
      run: cargo install cargo-ndk@3.5.4

    # ---------- Gradle ----------
    - name: Try to get a cached copy of Gradle
      id: cache-gradle
      uses: actions/cache@v3
      with:
        path: gradle
        key: gradle-8.11.1

    - if: ${{ steps.cache-gradle.outputs.cache-hit != 'true' }}
      name: Download Gradle
      run: curl -L -o gradle-8.11.1-bin.zip "https://services.gradle.org/distributions/gradle-8.11.1-bin.zip"

    - if: ${{ steps.cache-gradle.outputs.cache-hit != 'true' }}
      name: Extract Gradle
      run: 7z -ogradle x gradle-8.11.1-bin.zip

    # ---------- Android NDK ----------
    - name: Try to get a cached copy of Android NDK
      id: cache-android-ndk
      uses: actions/cache@v3
      with:
        path: android-ndk
        key: android-ndk-r25c

    - if: ${{ steps.cache-android-ndk.outputs.cache-hit != 'true' }}
      name: Download Android NDK
      run: curl -L -o android-ndk-r25c-linux.zip "https://dl.google.com/android/repository/android-ndk-r25c-linux.zip"

    - if: ${{ steps.cache-android-ndk.outputs.cache-hit != 'true' }}
      name: Extract Android NDK
      run: 7z -oandroid-ndk -snld x android-ndk-r25c-linux.zip

    - name: Link Android NDK
      run: ln -s $PWD'/android-ndk/android-ndk-r25c' $ANDROID_SDK_ROOT'/ndk/25.2.9519653'

    - name: Generate local.properties file
      run: echo 'sdk.dir='$ANDROID_SDK_ROOT > android/local.properties

    # ---------- Lint (32-bit ABI) ----------
    - name: Lint (ARMv7)
      run: dev-scripts/lint.sh ndk -t armeabi-v7a
      env:
        ANDROID_NDK_ROOT: '/usr/local/lib/android/sdk/ndk/25.2.9519653'
        ANDROID_NDK: '/usr/local/lib/android/sdk/ndk/25.2.9519653'
        ANDROID_NDK_HOME: '/usr/local/lib/android/sdk/ndk/25.2.9519653'
        CMAKE: ${{ github.workspace }}/vendor/cmake/bin/cmake

    # ---------- Build APK ----------
    - name: Build for Android (32-bit)
      run: |
        cd android
        ../gradle/gradle-8.11.1/bin/gradle assembleRelease
        mv app/build/outputs/apk/release/app-release.apk ../touchHLE-32bit.apk
      env:
        ANDROID_NDK_ROOT: '/usr/local/lib/android/sdk/ndk/25.2.9519653'
        CMAKE: ${{ github.workspace }}/vendor/cmake/bin/cmake

    - uses: actions/upload-artifact@v4
      with:
        name: touchHLE_Android_ARMv7_32bit
        path: touchHLE-32bit.apk
